# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "data experts"
email: office@data-experts.de
description: "A support page."
baseurl: "support_site"
url: ""
twitter_username: ""
github_username:  ""
color_theme:  "#006400"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
#permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
